"use client"

import { Roboto_Condensed } from 'next/font/google'


const roboto = Roboto_Condensed({
  weight: '400',
  subsets: ['latin'],
})

const metadata = {
  title: 'George\'s Personal Website',
  // description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}